# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc8a54d67c193ac7cf60dc3efe6bcf03a9399c37838c9313f2789c8f0b50e4521ad9ee85833382510437baedff44862455a27f12b4bcac86b09f5adddd449020

test:
  secret_key_base: 19d426f4edb73ffd6ab174f7c9e430083340026e9f8065fe29e10812b707cd1234ec1a037f4847f0933ab121f42c2b71c0e01f56e59429aed9d567a68f6f3f46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
